services:
  nginx:
    image: nginx:alpine
    ports:
      - "56566:443" # Expose HTTPS port
    volumes:
      - ../frontend/certs/server-cert.pem:/etc/ssl/certs/server-cert.pem
      - ../frontend/certs/server-key.pem:/etc/ssl/private/server-key.pem
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"